
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const UPDATE_USER_SUCCCESS = "UPDATE_USER_SUCCESS"
export const DELETE_USER_SUCCCESS = "DELETE_USER_SUCCCESS"